### ISSUE TITLE
Convert `configuration` documentation from AsciiDoc to markdown

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/documentation#21]
The couple of files in https://github.com/IntellectualSites/fastasyncworldedit-documentation/tree/main/sources/configuration need to be migrated to Markdown and put in place in a new `configuration` folder in https://github.com/IntellectualSites/documentation/tree/main/fastasyncworldedit/configuration

**Comment by specbeck** [comment]
Hi! I'd like to work on this please :)

**Comment by NotMyFault** [comment]
For sure, go ahead and raise a pull request :)
