### ISSUE TITLE
Link-ify PlotSquared external placeholder URLs

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/documentation#29]
Optimally, https://intellectualsites.gitbook.io/plotsquared/customization/placeholders#external-placeholders should be a clickable URL instead of plain text.

**Comment by Siddhu545** [comment]
!assign

**Comment by NotMyFault** [comment]
No need to assign yourself, simply start working on it by raising a PR :)

**Comment by Siddhu545** [comment]
Github repo?
