### ISSUE TITLE
Add a table of contents to pages

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/documentation#40]
gitbook renders the table of contents of pages by page name. Given, the file names are a single word only, it's hard to find what you are looking for.

To give pages a human-friendly name, there should be a `SUMMARY.md` located in every projects' folder, structuring the table of contents properly, like seen on https://docs.gitbook.com/integrations/git-sync/content-configuration#summary

**Comment by specbeck** [comment]
Are there specific page group headings to be included while structuring?

**Comment by NotMyFault** [comment]
At best, the page heading equals a brief one-liner of the page content, like a ToC.

**Comment by NotMyFault** [comment]
> I meant similar pages grouped together under a same heading. For example:
> 
> ### Group heading (Features/Under revision/Additional utilities)
> * Relevant Pages
>   
>   * Sub pages (if any)
> 
> Right now, there is no well defined grouping for the individual pages, so to group related pages under a same heading would be nice.

Yeah, that looks fine. Any sorting is better than what we have at the moment :P
