### ISSUE TITLE
Apply scaling to clipboard connect page image

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/documentation#69]
Opening the page displays a giant image https://intellectualsites.gitbook.io/clipboard-connect/readme

![Screenshot 2024-02-18 at 13 57 23](https://github.com/IntellectualSites/documentation/assets/13383509/d5441244-0d65-4ee3-80b5-3c6e70aee7d7)

The image should stick to the icon sizes found on the FAWE and P2 pages.

**Comment by NotMyFault** [comment]
FYI @IntellectualSites/clipboard-connect-developers

**Comment by OneLiteFeather** [comment]
Thank you, I'll do that today

**Comment by NotMyFault** [comment]
If you have a SVG of the icon, you may use that too.

**Comment by TheMeinerLP** [comment]
We have only PNG but we can resize it
