### ISSUE TITLE
grants are set to 0, when Player left the server and joined again

### ISSUE THREAD

**Issue by Anyali77** [IntellectualSites/documentation#81]
Everytime I give a player with the command /p grant add .... some grants, they will set to 0, if he leave the server and join again. They will set to 0 at the moment when the player joined. During he is left it is still there.

**Comment by dordsor21** [comment]
Please open this issue in P2 and follow the instructions in the issue template there https://github.com/IntellectualSites/PlotSquared/issues/new/choose
